#!/bin/sh

"${KAPPABIN}"KaSim -i model.ka -l 10 -u time -seed 886009874 -d output && "${KAPPABIN}"KaSim -i model.ka -l 15 -u time -mixture output/snap_75.ka -o data_2.csv -seed 886009874 -d output || exit 0
