#!/bin/sh

BUILDROOT=${KAPPABIN}../_build/

ledit ocamldebug -I ${BUILDROOT}dev -I ${BUILDROOT}grammar \
      -I ${BUILDROOT}pattern -I ${BUILDROOT}simulation \
      -I ${BUILDROOT}siteGraph -I ${BUILDROOT}datastructures \
      ${BUILDROOT}main/KaSim.byte $@
